name: Move Issue to Done

on:
  pull_request:
    types: [closed]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Move related issues to Done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo $GH_TOKEN | gh auth login --with-token
          issue_numbers=$(jq -r '.pull_request.body | scan("#([0-9]+)")' < "$GITHUB_EVENT_PATH")

          for issue_number in $issue_numbers; do
            # Find the project board
            project_query='{
              repository(owner: "meetgom", name: "2024-meetgom-frontend") {
                projectsV2(first: 1) {
                  nodes {
                    id
                  }
                }
              }
            }'
            project_id=$(curl -H "Authorization: token $GH_TOKEN" \
                          -X POST -d "{\"query\":\"$project_query\"}" \
                          https://api.github.com/graphql | jq -r '.data.repository.projectsV2.nodes[0].id')

            # Find the project item
            item_query='{
              repository(owner: "meetgom", name: "2024-meetgom-frontend") {
                issue(number: '$issue_number') {
                  projectItems(first: 1) {
                    nodes {
                      id
                    }
                  }
                }
              }
            }'
            item_id=$(curl -H "Authorization: token $GH_TOKEN" \
                         -X POST -d "{\"query\":\"$item_query\"}" \
                         https://api.github.com/graphql | jq -r '.data.repository.issue.projectItems.nodes[0].id')

            # Move the project item to Done column
            mutation='mutation {
              updateProjectV2ItemFieldValue(input: {
                projectId: "'$project_id'",
                itemId: "'$item_id'",
                fieldValue: {
                  singleSelectOptionId: "98236657"
                }
              }) {
                projectV2Item {
                  id
                }
              }
            }'
            curl -H "Authorization: token $GH_TOKEN" \
                 -X POST -d "{\"query\":\"$mutation\"}" \
                 https://api.github.com/graphql
          done
